
export const B2W_RATES = [
    { category: 'Telefonia Fixa / Celular', rate: 0.16 },
    { category: 'Eletrodomésticos / Eletrônicos', rate: 0.16 },
    { category: 'Informática / Acessórios', rate: 0.16 },
    { category: 'Alimentos / Bebidas', rate: 0.16 },
    { category: 'Pet Shop', rate: 0.16 },
    { category: 'Móveis / Papelaria / Instrumentos', rate: 0.165 },
    { category: 'Brinquedos / Bebês', rate: 0.165 },
    { category: 'Automotivo / Artesanato', rate: 0.165 },
    { category: 'Higiene / Beleza / Saúde', rate: 0.17 },
    { category: 'Livros', rate: 0.17 },
    { category: 'Esporte / Lazer / Ferramentas', rate: 0.17 },
    { category: 'Moda / Acessórios / Calçados', rate: 0.19 },
    { category: 'Relógios', rate: 0.19 },
];

export const AMAZON_RATES = [
    { category: 'Comidas e Bebidas', rate: 0.10, minFee: 1.00 },
    { category: 'Eletrodomésticos de Linha Branca', rate: 0.11, minFee: 1.00 },
    { category: 'Saúde e Cuidados Pessoais', rate: 0.12, minFee: 1.00 },
    { category: 'Bebidas Alcoólicas', rate: 0.11, minFee: 1.00 },
    { category: 'Pneus e Rodas', rate: 0.10, minFee: 1.00 },
    { category: 'Indústria e Ciência', rate: 0.12, minFee: 1.00 },
    { category: 'Produtos para Bebês', rate: 0.12, minFee: 2.00 },
    { category: 'Produtos para Animais de Estimação', rate: 0.12, minFee: 2.00 },
    { category: 'Cozinha / Jardim / Casa', rate: 0.12, minFee: 2.00 },
    { category: 'Brinquedos e Jogos', rate: 0.12, minFee: 2.00 },
    { category: 'TV, Áudio e Cinema em Casa', rate: 0.10, minFee: 2.00 },
    { category: 'PC', rate: 0.12, minFee: 2.00 },
    { category: 'Eletrônicos Portáteis', rate: 0.13, minFee: 2.00 },
    { category: 'Peças e Acessórios Automotivos', rate: 0.12, minFee: 2.00 },
    { category: 'Beleza', rate: 0.13, minFee: 2.00 },
    { category: 'Beleza de Luxo', rate: 0.14, minFee: 2.00 },
    { category: 'Celulares', rate: 0.11, minFee: 2.00 },
    { category: 'Câmera e Fotografia', rate: 0.11, minFee: 2.00 },
    { category: 'Videogames e Consoles', rate: 0.11, minFee: 2.00 },
    { category: 'Esportes, Aventura e Lazer', rate: 0.12, minFee: 2.00 },
    { category: 'Ferramentas e Construção', rate: 0.11, minFee: 2.00 },
    { category: 'Papelaria e Escritório', rate: 0.13, minFee: 2.00 },
    { category: 'Roupas, Calçados, Bolsas, Relógios, Joias', rate: 0.14, minFee: 2.00 }, // Simplified
    { category: 'Livros', rate: 0.15, minFee: 2.00 },
    { category: 'Acessórios para Eletrônicos (Tiered)', rate: 0.15, minFee: 2.00, tiered: { threshold: 100, aboveRate: 0.10 } },
    { category: 'Móveis (Tiered)', rate: 0.15, minFee: 2.00, tiered: { threshold: 200, aboveRate: 0.10 } },
    { category: 'Vídeo, DVD, Música', rate: 0.15, minFee: 2.00 },
    { category: 'Instrumentos Musicais', rate: 0.12, minFee: 2.00 },
    { category: 'Demais Categorias', rate: 0.15, minFee: 2.00 },
];
